### PR TITLE
Add live star-history graph

### PR DESCRIPTION
**Pull request by tianzhou**

### CODE REVIEW

**Comment by JWittmeyer** [comment]
Hi tianzhou, 

thanks for the contribution. Two small things.
1. would you also add the Star History to the table of content
2. We have a Team & contributed section. If you want you can add yourself there with e.g. your Profilphoto and a link to your GitHub/Linked or whatever fits for you. This is of course totally voulentary 


- [ ] resolved

**Comment by tianzhou** [comment]
Added TOC. PTAL.

**Comment by JWittmeyer** [comment]
> Added TOC. PTAL.

Just to be sure this means you don't want to be listed in the contribute section?

**Comment by tianzhou** [comment]
> > Added TOC. PTAL.
> 
> Just to be sure this means you don't want to be listed in the contribute section?

Right, it's just a small contribution.

**Pull request merged**
